### ISSUE TITLE
Text repeated in every tweet

### ISSUE THREAD

**Issue by KNTRO** [ciderpunx/twitrssme#44]
Hello!

I'd like to report that every tweet's text is repeated.

The original text has this format:
[tweet text]
[tweet URL]
[date & time]

Then there's an empty line, and then it repeats:
[tweet text]

So you got this:
[tweet text]
[tweet URL]
[date & time]
[empty line]
[tweet text again]

Here's an example:
```
【かわいい #猫動画 】幽体離脱中の猫 - funny Cats’ spirit appears? - #猫好きさんと繋がりたい #catlovers #caturday https://youtu.be/L4LgX8F0kFg 
https://twitter.com/Udon_Prfm/status/960048223451664384
Feb 4th 2018, 04:11

【かわいい #猫動画 】幽体離脱中の猫 - funny Cats' spirit appears? - #猫好きさんと繋がりたい #catlovers #caturday https://youtu.be/L4LgX8F0kFg
```

Could you fix this, please?

Thanks a lot in advance!

**Comment by ciderpunx** [comment]
This is the expected behaviour and compatible with Twitter's original RSS feed implementation. 

If you look at the XML one instance is the item title and one is the item description. There's no sensible alternative to using the tweet text for the title and description fields apart from maybe something like the Tweet ID, but at this stage we'd most likely break things for people who are relying on TwitRSS's existing behaviour.
