### ISSUE TITLE
New Twitter, new problem

### ISSUE THREAD

**Issue by crockpoot** [ciderpunx/twitrssme#75]
Just noticed that Twitter has a new UI. I don't hate it but what I do hate is that I received none of my usual Twitter feeds today. I assume the two are connected.

**Comment by ciderpunx** [comment]
Yes, I'm afraid it looks like they broke things for us again. 

I'll need to refactor the code, which isn't likely before the weekend. 

For now the workaround is to use the mobile version  of the code. Change the /twitter_user_to_rss in your URL to mobile_twitter_to_rss and you should be OK for now. 

I've not rewritten search yet, so that'll remain broken for now. Sorry about that! 

I'll update the front page of the site to use the mobile code.

**Comment by micressor** [comment]
@ciderpunx It looks like [apache.conf](https://github.com/ciderpunx/twitrssme/blob/master/apache.conf) is not updated for the `/mobile_twitter_to_rss`?

**Comment by Omnialias** [comment]
Something that tripped me up a little that is worth mentioning here: the syntax of the value of the <dc:creator> element when using mobile_twitter_to_rss.pl is different and includes the "friendly name" on Twitter, not just the username.

**Comment by dperelman** [comment]
I was able to fix it on my end by just enabling cookie support when screenscraping: bd3e47c08c36ea6ef78e24fc01abdf59f34b9b6b . I'll make a PR in a moment.

**Comment by fabrei** [comment]
> For now the workaround is to use the mobile version of the code. Change the /twitter_user_to_rss in your URL to mobile_twitter_to_rss and you should be OK for now.

thanks for your suggestion to change it to `/mobile_twitter_to_rss` ..but it only works once for a little while..it worked today in the morning with one twitter account. afterwards, it didn't work with another. but after more or less exactly 5 hours it worked with another account. is there a kind of time frame to wait until it works again?

**Comment by 1lomeno3** [comment]
Any update on this? The workaround does not work for me :(

**Comment by dperelman** [comment]
@1lomeno3 By "the workaround" are you referring to `/mobile_twitter_to_rss`, my PR, or both? [My branch](https://github.com/dperelman/twitrssme) has some of my own changes which I believe are unrelated, but it's currently working for me.

**Comment by Omnialias** [comment]
I made the changes that you added in your PR @dperelman and am getting the same problems that @fabrei has. Specifically, it seems like cookie caching might be getting in the way of something? I have found that I have to browse to the RSS feed, refresh it a few times, then it'll grab the RSS. This works for a day or so, then breaks and I have to go and refresh that RSS feed again.

**Comment by dperelman** [comment]
Oh. I see. The way I'm using it (calling it directly from Liferea, not hosting it on a web server), I only ever make one request per invocation of the script, but it actually handles requests in a loop. My PR initializes the cookie jar outside of the loop. If you instead move
```perl
$browser->cookie_jar( {} );
```
to immediately before
```perl
my $response = $browser->get($url);
```
then it should clear cookies before every request, which might get better behavior. I'll update my PR.

**Comment by ciderpunx** [comment]
So I believe that #76 and #77 combined resolve the issue for now. 

My apologies for being so slow to respond, I've been AFK for a while for various reasons and not keeping as much of an eye on TwitRSS as I should have. 

In the long run, I want to do a proper refactor with the idea that the parser/fetchers can be modules used by the cgi process rather than part of the controller script itself.
