### ISSUE TITLE
umlauts broken

### ISSUE THREAD

**Issue by pattyland** [ciderpunx/twitrssme#9]
All umlauts are broken, e.g. `Ich habe k&#xFC;rzlich gekauft: &#x27;Fire TV Stick&#x27; von Amazon &#xFC;ber @amazon`

**Comment by t3chguy** [comment]
+1
Since the data seems already encapsulated within CDATA, it doesn't need further escaping.
Facebook has a similar issue back when they served RSS and they classed it as a Bug, but denied to fix it as it was found within 90 days of the end of life of the RSS Feeds anyway.

I'd really appreciate it if you could look into this as it isn't only on foreign characters, it happens on things like ' single quotes also

**Comment by ciderpunx** [comment]
Thanks for the report, will have a poke about and see what I can do...

**Comment by ciderpunx** [comment]
I've fixed this by numerically encoding high-bit characters and /not/ wrapping in cdata declarations. just testing on accounts like http://twitrss.me/twitter_user_to_rss/?user=derspiegel

**Comment by ciderpunx** [comment]
OK, fixed in this commit; should be live on twitrss.me in about 24 hours.
https://github.com/ciderpunx/twitrssme/commit/b8e2a52b4b095f2378211056a9e9a4bceefb07de
